# Generated by Django 4.2.28 on 2026-03-04 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doit_app', '0003_savedlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedListTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saved_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='doit_app.savedlist')),
            ],
            options={
                'ordering': ['is_completed', 'created_at'],
            },
        ),
    ]
