# Generated by Django 4.2.28 on 2026-03-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit_app', '0004_savedlisttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedlist',
            name='focus_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='savedlist',
            name='notes_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
